# Generated by Django 4.1.1 on 2022-09-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_choice',
            field=models.CharField(choices=[('debit card', 'debit card'), ('cash', 'cash'), ('e-wallet', 'e-wallet')], default='cash', max_length=200, null=True),
        ),
    ]
