# Generated by Django 4.1.1 on 2022-09-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0001_initial'),
        ('payment', '0002_alter_payment_payment_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_categories',
            field=models.ForeignKey(default='NULL', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pocket.pocket'),
        ),
    ]
