# Generated by Django 4.1.1 on 2022-09-30 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_alter_payment_pay_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user_payment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
