# Generated by Django 4.1.1 on 2022-12-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='newsletter_title',
            field=models.TextField(default='', max_length=100),
        ),
    ]
