# Generated by Django 4.1.1 on 2022-11-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_category',
            field=models.CharField(choices=[('tips', 'tips'), ('news', 'news')], default='tips', max_length=10),
        ),
    ]
