# Generated by Django 4.1.1 on 2022-12-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_picture',
            field=models.ImageField(blank=True, null=True, upload_to='newsletter/pictures/'),
        ),
    ]
