# Generated by Django 4.1.1 on 2022-11-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newsletter_newsletter_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_picture',
            field=models.ImageField(default='newsletter/pictures/default.jpg', upload_to='newsletter/pictures'),
        ),
    ]
