# Generated by Django 4.1.1 on 2022-11-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_alter_newsletter_newsletter_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_picture',
            field=models.ImageField(blank=True, default='newsletter/pictures/default.png', upload_to='newsletter/pictures'),
        ),
    ]
