# Generated by Django 4.1.1 on 2022-11-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_alter_newsletter_newsletter_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_picture',
            field=models.ImageField(blank=True, null=True, upload_to='newsletter/pictures/'),
        ),
    ]
