# Generated by Django 3.2.7 on 2022-10-06 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_payment_name', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('transaction_amount', models.BigIntegerField(default=False)),
                ('transaction_date', models.DateField()),
                ('transaction_type_transaction', models.CharField(max_length=50)),
                ('transaction_type_payment', models.CharField(max_length=50)),
                ('user_transaction', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
