# Generated by Django 3.2.7 on 2022-10-06 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0002_alter_pocket_pocket_name'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_pocket',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='pocket.pocket'),
        ),
    ]
