# Generated by Django 3.2.7 on 2022-10-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20221008_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_payment_type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], default='cash', max_length=200, null=True),
        ),
    ]
