# Generated by Django 4.1.1 on 2022-12-27 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('customer_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('feedback_rating', models.IntegerField(default=0)),
                ('feedback_goal', models.TextField(default='', max_length=100)),
                ('feedback_text', models.TextField(default='', max_length=100)),
                ('feedback_text2', models.TextField(default='', max_length=100)),
                ('feedback_comment', models.TextField(default='', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_feedback', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
