# Generated by Django 3.2.7 on 2022-10-25 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_feature', models.CharField(choices=[('payment', 'payment'), ('pocket', 'pocket'), ('transaction', 'transaction'), ('expense', 'expense'), ('financialreport', 'financialreport'), ('transaction', 'transaction')], default='payment', max_length=200, null=True)),
                ('feedback_textbox', models.TextField()),
                ('user_feedback', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
