# Generated by Django 4.1.1 on 2022-12-23 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_rating', models.IntegerField(default=0)),
                ('feedback_goal', models.TextField(default='', max_length=100)),
                ('feedback_text', models.TextField(default='', max_length=100)),
                ('feedback_text2', models.TextField(default='', max_length=100)),
                ('feedback_comment', models.TextField(default='', max_length=100)),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('user_feedback', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
