# Generated by Django 4.1.1 on 2022-12-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackreport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer_ID',
            field=models.AutoField(default=2, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
