# Generated by Django 4.1.1 on 2022-12-23 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackreport', '0002_remove_feedback_id_feedback_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_date',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedbackdate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
