# Generated by Django 4.1.1 on 2022-12-23 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackreport', '0003_remove_feedback_feedback_date_feedback_feedbackdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedbackdate',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
