# Generated by Django 4.1.1 on 2022-12-23 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackreport', '0004_remove_feedback_feedbackdate_feedback_feedback_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_date',
        ),
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
