# Generated by Django 4.1.1 on 2022-12-27 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('pocket_name', models.CharField(blank=True, default='Pocket', max_length=50, primary_key=True, serialize=False)),
                ('pocket_budget', models.BigIntegerField(default=False)),
                ('pocket_balance', models.BigIntegerField(default=0)),
                ('pocket_default', models.BigIntegerField(default=0)),
                ('user_pocket', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
