<<<<<<< HEAD
# Generated by Django 3.2.8 on 2022-09-21 15:34
=======
# Generated by Django 4.1.1 on 2022-09-21 16:39
>>>>>>> 30a36af1e6c0370618ba66dedc282973317bb6a2

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('budget', models.BigIntegerField()),
            ],
        ),
    ]
