# Generated by Django 4.1.1 on 2022-10-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocket',
            name='pocket_name',
            field=models.CharField(blank=True, default='Pocket', max_length=50, primary_key=True, serialize=False),
        ),
    ]
