# Generated by Django 3.2.8 on 2022-09-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pocket',
            old_name='budget',
            new_name='pocket_budget',
        ),
        migrations.RenameField(
            model_name='pocket',
            old_name='name',
            new_name='pocket_name',
        ),
    ]
