# Generated by Django 3.2.7 on 2022-10-02 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pocket', '0002_auto_20220926_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pocket',
            old_name='pocket_budget',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='pocket',
            old_name='pocket_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='pocket',
            name='user_pocket',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
