# Generated by Django 3.2.7 on 2022-10-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0003_auto_20221003_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocket',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='pocket',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pocket',
            name='name',
        ),
        migrations.AddField(
            model_name='pocket',
            name='pocket_balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pocket',
            name='pocket_budget',
            field=models.BigIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='pocket',
            name='pocket_name',
            field=models.CharField(blank=True, default='Pocket', max_length=50, primary_key=True, serialize=False),
        ),
    ]
